---
- name: Local tasks
  hosts: localhost
  connection: local
  tasks:
  - name: Wait for SSH to come up on coordinator
    wait_for: host={{ COORDINATOR_NAME }} port=22 delay=60 timeout=300 state=started
    sudo: false
    tags: post-start

- name: Remote tasks
  hosts: all
  remote_user: ubuntu
  sudo: yes
  gather_facts: false
  roles:
  - name: myria-web

- name: display connection information for coordinator
  hosts: localhost
  connection: local
  tags: post-start
  tasks:
    # REST service may not be available immediately after myria service starts
    - wait_for: host={{ COORDINATOR_NAME }} port={{ myria_rest_port }} delay=60 timeout=300 state=started
      sudo: false
    - shell: "echo http://{{ COORDINATOR_NAME }}:{{ myria_web_port }} > /tmp/{{CLUSTER_NAME}}-myria-web.url"
    - shell: "echo http://{{ COORDINATOR_NAME }}:{{ myria_rest_port }} > /tmp/{{CLUSTER_NAME}}-myria-rest.url"
    - shell: "echo http://{{ COORDINATOR_NAME }}:{{ ganglia_web_port }} > /tmp/{{CLUSTER_NAME}}-ganglia-web.url"
    - shell: "echo {{ COORDINATOR_NAME }} > /tmp/{{CLUSTER_NAME}}-myria-ssh-user-host.txt"
