---
- name: restart apache
  action: service name=apache2 state=restarted
  when: is_debian_or_ubuntu

- name: restart gmond
  action: command service ganglia-monitor restart

- name: restart gmetad
  action: command service gmetad restart
  when: '"coordinator_name" in group_names'
