---
- name: disable ssh host key checking # this is excessive, fix this to be restricted to the list of IPs deployed
  shell: (echo Host *; echo StrictHostKeyChecking no; echo UserKnownHostsFile=/dev/null) >> /etc/ssh/ssh_config
  sudo: yes

- name: add Java8 PPA
  apt_repository: repo='ppa:webupd8team/java'

- name: Automatically select the Oracle license for Java
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'

# The Oracle download site is very flaky and there are no mirrors,
# so we copy the Java SDK tarball to /var/cache/oracle-jdk8-installer/
# before installing the oracle-java8-installer package.

- name: Create oracle-java8-installer package cache directory since it doesn't exist yet
  file: path='/var/cache/oracle-jdk8-installer' state=directory mode=0755 owner='root' group='root'
  sudo: yes

- name: Cache JDK8 tarball to avoid Oracle download
  get_url: url='{{ jdk8_url }}' dest='{{ jdk8_file }}' mode=0644 validate_certs=no timeout=300
  sudo: yes

- name: Installing packages
  apt: name="{{item}}" state=latest update_cache=yes
  with_items:
    - git
    - zip
    - unzip
    - oracle-java8-installer
    - oracle-java8-set-default
    - libxml2-dev
    - libxslt1-dev
    - python-dev
