---
- name: Install ganglia monitor 
  action: apt pkg={{item}} state=latest update_cache=yes
  with_items:
    - ganglia-monitor

- name: Configure gmond
  action: template src=roles/ganglia-client/templates/gmond.conf.j2 dest=/etc/ganglia/gmond.conf
  notify:
    - restart gmond
    - restart gmetad
