---
#install ganglia on the myria coordinator
#tasks
  
- name: Installing packages - ganglia server
  apt: name="{{item}}" update_cache=yes
  with_items:
    - ganglia-monitor
    - rrdtool
    - gmetad
    - ganglia-webfrontend

- name: Configure apache link (conf-available)
  action: file src=/etc/ganglia-webfrontend/apache.conf dest=/etc/apache2/conf-available/ganglia.conf state=link


- name: Configure apache link (conf-enabled)
  action: file src=/etc/apache2/conf-available/ganglia.conf dest=/etc/apache2/conf-enabled/ganglia.conf state=link
  notify: restart apache


- name: Configure gemetad
  action: template src=roles/ganglia/templates/gmetad.conf.j2 dest=/etc/ganglia/gmetad.conf
  notify: restart gmetad
