---
# configuring myria on the coordinator node
# clone git repo, build, create deployment config, setup and launch cluster.

- name: Installing packages
  apt: name="{{item}}" update_cache=yes
  with_items:
    - git

- name: Clone Myria repository
  sudo: no
  git: repo="{{myria_repository_url}}"
           dest="{{myria_path}}"
           version="{{myria_branch}}"

- name: Compile Myria
  shell: "./gradlew shadowJar"
  sudo: no
  args:
    chdir: "{{myria_path}}"
    creates: "{{myria_path}}/build/libs"

- name: Create deployment configuration file
  shell: "./create_deployment.py {{myria_path}} {{ groups['coordinator_name'] | join(' ') }} \
                                                    {{ groups['worker_names'] | join(' ') }} \
                                                    --rest-port {{rest_port}} \
                                                    --coordinator-port {{coordinator_port}} \
                                                    --worker-base-port {{worker_base_port}} \
                                                    --database-password {{database_password}} \
                > {{myria_path}}/myriadeploy/deployment.cfg"
  sudo: no
  args:
    chdir: "{{myria_path}}/myriadeploy"
    creates: "{{myria_path}}/myriadeploy/deployment.cfg"

- name: Launch cluster
  shell: ". {{ common['soft_link_base_path'] }}/hadoop/env.sh && {{ common['soft_link_base_path'] }}/hadoop/bin/yarn jar {{myria_path}}/build/libs/myria-0.1-all.jar edu.washington.escience.myria.daemon.MyriaDriverLauncher -runtimeClass org.apache.reef.runtime.yarn.client.YarnClientConfiguration -configPath {{myria_path}}/myriadeploy -javaLibPath {{myria_path}}/build/libs -nativeLibPath {{myria_path}}/lib"
  sudo: no
  args:
    chdir: "{{myria_path}}/myriadeploy"
