---
# configuring myria on the coordinator node
# clone git repo, build, create deployment config, setup and launch cluster.

- name: Installing packages
  apt: name="{{item}}" update_cache=yes
  with_items:
    - git

- name: Create Myria source directory
  file: path={{myria_path}} state=directory owner={{myria_user}} group={{myria_group}} mode=0775

- name: Clone Myria repository
  git: repo="{{myria_repository_url}}" dest="{{myria_path}}" version="{{myria_branch}}"
  notify: restart myria

- name: Compile Myria
  shell: "./gradlew shadowJar"
  args:
    chdir: "{{myria_path}}"
    creates: "{{myria_path}}/build/libs"
  notify: restart myria

- name: Create deployment configuration file
  shell: "./create_deployment.py {{myria_path}} {{ hostvars[groups['tag_cluster_role_coordinator'][0]]['ansible_ec2_local_hostname'] }} \
                                                    {% for host in groups['tag_cluster_role_worker'] %} {{ hostvars[host]['ansible_ec2_local_hostname'] }} {% endfor %} \
                                                    --rest-port {{myria_rest_port}} \
                                                    --coordinator-port {{coordinator_port}} \
                                                    --worker-base-port {{worker_base_port}} \
                                                    --database-password {{database_password}} \
                                                    --container-memory-size-gb {{container_mem_gb}} \
                                                    --container-vcores-number {{container_vcores}} \
                                                    --persist-uri hdfs://{{hostvars[groups['tag_cluster_role_coordinator'][0]]['ansible_ec2_local_hostname']}}:{{namenode_port}}
                > {{myria_path}}/myriadeploy/deployment.cfg"
  args:
    chdir: "{{myria_path}}/myriadeploy"
    creates: "{{myria_path}}/myriadeploy/deployment.cfg"
  notify: restart myria

- name: Install Myria service
  template: src=service.conf.j2 dest=/etc/init/myria.conf backup=yes mode=0644
  notify: restart myria

- name: Bounce Myria service on retry
  command: /bin/true
  notify: restart myria
