---
##
###installing and configuring postgres for myria
## 

- name: Adding APT repository key
  when: ansible_os_family == 'Debian'
  sudo: yes
  apt_key:
    id: ACCC4CF8
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
  tags:
    - postgresql
    - db
    - repo

- name: Add PostgreSQL official APT repository
  when: ansible_os_family == 'Debian'
  sudo: yes
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ {{ansible_distribution_release}}-pgdg main"
  tags:
    - postgresql
    - db
    - repo

- name: Install PostgreSQL
  when: ansible_os_family == 'Debian'
  sudo: yes
  apt:
    name: "postgresql-{{postgres_version}}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - postgresql
    - db
    - deps

- name: Install dependencies for the Ansible module
  when: ansible_os_family == 'Debian'
  sudo: yes
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - python-psycopg2
    - libpq-dev
  tags:
    - postgresql
    - db
    - deps

- name: altering postgres conf- adding listeners 
  lineinfile: dest=/etc/postgresql/{{postgres_version}}/main/postgresql.conf
                regexp="^listen_addresses"
                line="listen_addresses = '*'" state=present
                backup=yes

- name: altering pg_hba.conf- adding listeners 
  lineinfile: dest=/etc/postgresql/{{postgres_version}}/main/pg_hba.conf
                line="host    all   all        0.0.0.0/0   md5" state=present
                backup=yes

- name: Create database instance
  postgresql_db: name={{database_name}}
  become_user: postgres

- name: Create database user
  postgresql_user: db={{database_name}} name={{database_username}} password={{database_password}} priv=ALL
  become_user: postgres

- name: Create Myria group
  group: name=myria state=present

- name: Create worker directory
  file: path={{myria_path}} state=directory owner={{myria_user}} group=myria mode=0775

- name: Restart Postgres
  service: name=postgresql state=restarted
