---
- name: Create a Group `"{{ hadoop_group }}"` for all our Hadoop Modules.
  group: name={{ hadoop_group }} state=present

- name: Create a User `"{{ hadoop_user }}"` for all our Hadoop Modules.
  user: name={{ hadoop_user }} group={{ hadoop_group }} password={{ hadoop_password }}

- name: Download Hadoop
  get_url: url=http://apache.osuosl.org/hadoop/common/hadoop-{{ hadoop_version }}/hadoop-{{ hadoop_version }}.tar.gz dest=/mnt/hadoop-{{ hadoop_version }}.tar.gz mode=0644 validate_certs=no timeout=300

- name: Copying and unarchive Hadoop in destination folder
  unarchive: creates={{ common['install_base_path'] }}/hadoop-{{ hadoop_version }} copy=no src=/mnt/hadoop-{{ hadoop_version }}.tar.gz dest={{ common['install_base_path'] }} owner={{ hadoop_user }} group={{ hadoop_group }}

- name: Create directories
  file: path={{ item.path }} state=directory mode={{ item.mode }}
  with_items:
          - { path: "{{ common['install_base_path'] }}/hadoop-{{ hadoop_version }}/pbin", mode: '0755' }
          - { path: "{{ common['install_base_path'] }}/hadoop-{{ hadoop_version }}/etc/hadoop", mode: '0755' }
          - { path: "{{ cgroups_mount_dir }}", mode: '0755' }
          - { path: "{{ cgroups_mount_dir }}/cpu", mode: '0755' }
          - { path: "{{ cgroups_mount_dir }}/net_cls", mode: '0755' }
          - { path: "/mnt/data", mode: '0755' }
          - { path: "/mnt/nm-local", mode: '0755' }

- name: Change Directory Permissions.
  file: path={{ common['install_base_path'] }}/hadoop-{{ hadoop_version }} owner={{ hadoop_user }} group={{ hadoop_group }} recurse=yes

- name: Creating a Symbolic Link in {{ common['soft_link_base_path'] }}/hadoop.
  file: src={{ common['install_base_path'] }}/hadoop-{{ hadoop_version }} path={{ common['soft_link_base_path'] }}/hadoop state=link owner={{ hadoop_user }} group={{ hadoop_group }}

- name: Change Directory Permissions.
  file: path={{ item.path }} owner={{ hadoop_user }} group={{ hadoop_group }} mode={{ item.mode }} recurse=yes
  with_items:
          - { path: "/mnt/data", mode: '0755' }
          - { path: "/mnt/nm-local", mode: '0755' }

- name: Copying templated provisioning scripts
  template: src={{ item.src }} dest="{{ common['install_base_path'] }}/hadoop-{{ hadoop_version }}/pbin" mode=0755
  with_items:
          - { src: 'hadoop-config.sh', dest: 'hadoop-config.sh' }
          - { src: 'provision-hadoop.sh', dest: 'provision-hadoop.sh' }

- name: Copying templated control scripts
  template: src={{ item.src }} dest="{{ common['install_base_path'] }}/hadoop-{{ hadoop_version }}/pbin" mode=0755
  with_items:
          - { src: 'restart-hadoop-master-daemons.sh', dest: 'restart-hadoop-master-daemons.sh' }
          - { src: 'restart-hadoop-slave-daemons.sh', dest: 'restart-hadoop-slave-daemons.sh' }

- name: Change Directory Permissions.
  file: path={{ common['install_base_path'] }}/hadoop-{{ hadoop_version }}/pbin owner={{ hadoop_user }} group={{ hadoop_group }} recurse=yes

- name: Copying configuration/archive/control scripts
  template: src={{ item.src }} dest="{{ common['install_base_path'] }}/hadoop-{{ hadoop_version }}/etc/hadoop" mode={{ item.mode }}
  with_items:
          - { src: 'container-executor.cfg', mode: '0644' }
          - { src: 'core-default.xml', mode: '0644' }
          - { src: 'core-site.xml', mode: '0644' }
          - { src: 'yarn-default.xml', mode: '0644'  }
          - { src: 'yarn-site.xml', mode: '0644'  }
          - { src: 'mapred-site.xml', mode: '0644'  }

- name: Provision Hadoop 
  shell: "{{ common['soft_link_base_path'] }}/hadoop/pbin/provision-hadoop.sh"
  sudo: yes
